baseURL = "/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Amazon SageMaker Workshop"
theme = "hugo-theme-learn"
uglyurls = true
googleAnalytics = "UA-119576367-1"

[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = false
author = "Daniele Stroppa"
description = "Amazon SageMaker Workshop"
disableSearch = false
disableAssetsBusting = false
disableLandingPageButton = true
disableShortcutsTitle=true
disableLanguageSwitchingButton = false

[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[[menu.shortcuts]]
name = "<i class='fa-solid fa-globe'></i> Web site"
identifier = "ws"
url = "https://www.smartworkz.nl"
weight = 1

[[menu.shortcuts]]
name = "<i class='fa-brands fa-linkedin'></i> LinkedIn"
identifier = "li"
url = "https://www.linkedin.com/company/smartworkznl"
weight = 2

[[menu.shortcuts]]
name = "<i class='fa-brands fa-github'></i> GitHub"
identifier = "gh"
url = "https://github.com/smartworkz-kyriacos/sagemaker-workshop.git"
weight = 3



